export const sample_filters = [
    {
        num: '1',
        product_id: '014520-2370',
        product_name: "ฟิลเตอร์แอร์ DENSO TOYOTA HILUX VIGO",
        imageUrl:'test.jpg',
    },
    {
        num: '2',
        product_id: "014520-2651",
        product_name: "ฟิลเตอร์แอร์ DENSO TOYOTA YARIS,VIOS'07",
        imageUrl:'F-036.jpg',
    },
    {
        num: '3',
        product_id: "144531-1740",
        product_name: "COVER TOYOTA VIGO(DENSO)",
        imageUrl:'F-036.jpg',
    },
    {
        num: '4',
        product_id: "145520-2370",
        product_name: "กรองแอร์ TOYOTA HILUX",
        imageUrl:'F-036.jpg',
    },
    {
        num: '5',
        product_id: "145531-1380",
        product_name: "ฝาปิด DENSO CAMRY'06",
        imageUrl:'F-036.jpg',
    },
    {
        num: '6',
        product_id: "145531-1441",
        product_name: "ฝาปิด TOYOTA YARIS,VIOS",
        imageUrl:'F-036.jpg',
    },
    {
        num: '7',
        product_id: "145531-1740",
        product_name: "ฝาปิด TOYOTA VIGO,FORTUNER (DENSO)",
        imageUrl:'F-036.jpg',
    },
    {
        num: '8',
        product_id: "145531-22744D",
        product_name: "ฝาปิด TOYOTA REVO ของแท้",
        imageUrl:'F-036.jpg',
    },
    {
        num: '9',
        product_id: "27276-1HA0A",
        product_name: "ฝาปิดสำหรับ NISSAN MARCH แท้",
        imageUrl:'F-036.jpg',
    },
    {
        num: '10',
        product_id: "27276-3TU0A",
        product_name: "ฝาปิดสำหรับ NISSAN TEANA'14(L33) ของแท้",
        imageUrl:'F-036.jpg',
    },
    {
        num: '11',
        product_id: "27276-4JA0A",
        product_name: "COVER NISSAN NAVARA NP300 ของแท้",
        imageUrl:'F-036.jpg',
    },
    {
        num: '12',
        product_id: "27276-JNZ0A",
        product_name: "ฝาปิดสำหรับ NISSAN TEANA'09 แท้",
        imageUrl:'F-036.jpg',
    },
    {
        num: '13',
        product_id: "52091300",
        product_name: "ฝาปิดตู้แอร์ ISUZU DDI 1.9,CHEV COROLADO แท้",
        imageUrl:'F-036.jpg',
    },
    {
        num: '14',
        product_id: "7801A856",
        product_name: "ฝาปิดตู้แอร์ MITSU MITSU MIRAGE,ATTRAGE,X-PANDER แท้",
        imageUrl:'F-036.jpg',
    },
    {
        num: '15',
        product_id: "C-001",
        product_name: "COVER TOYOTA VIGO(KM)",
        imageUrl:'F-036.jpg',
    },
    {
        num: '16',
        product_id: "C-002",
        product_name: "COVER ISUZU D-MAX'03 แบบแบน",
        imageUrl:'F-036.jpg',
    },
    {
        num: '17',
        product_id: "C-003",
        product_name: "COVER ISUZU D-MAX'12 แบบฝาสีขาวคู่กับ F-015",
        imageUrl:'F-036.jpg',
    },
    {
        num: '18',
        product_id: "C-004",
        product_name: "COVER MITSU TRTION'04-'14",
        imageUrl:'F-036.jpg',
    },
    {
        num: '19',
        product_id: "C-005",
        product_name: "COVER BRIO AMAZE BR-V MIBOLIO",
        imageUrl:'F-036.jpg',
    },
    {
        num: '20',
        product_id: "C-006",
        product_name: "ถาดสำหรับ HONDA JAZZ,CITY'03 (ALGOTECH)",
        imageUrl:'F-036.jpg',
    },
]