export const sample_filters = [
    {
        id: '1',
        p_code: '014520-2370',
        p_name: "ฟิลเตอร์แอร์ DENSO TOYOTA HILUX VIGO",
        imageUrl:'test.jpg',
    },
    {
        id: '2',
        p_code: "014520-2651",
        p_name: "ฟิลเตอร์แอร์ DENSO TOYOTA YARIS,VIOS'07",
        imageUrl:'F-036.jpg',
    },
    {
        id: '3',
        p_code: "144531-1740",
        p_name: "COVER TOYOTA VIGO(DENSO)",
        imageUrl:'F-036.jpg',
    },
    {
        id: '4',
        p_code: "145520-2370",
        p_name: "กรองแอร์ TOYOTA HILUX",
        imageUrl:'F-036.jpg',
    },
    {
        id: '5',
        p_code: "145531-1380",
        p_name: "ฝาปิด DENSO CAMRY'06",
        imageUrl:'F-036.jpg',
    },
    {
        id: '6',
        p_code: "145531-1441",
        p_name: "ฝาปิด TOYOTA YARIS,VIOS",
        imageUrl:'F-036.jpg',
    },
    {
        id: '7',
        p_code: "145531-1740",
        p_name: "ฝาปิด TOYOTA VIGO,FORTUNER (DENSO)",
        imageUrl:'F-036.jpg',
    },
    {
        id: '8',
        p_code: "145531-22744D",
        p_name: "ฝาปิด TOYOTA REVO ของแท้",
        imageUrl:'F-036.jpg',
    },
    {
        id: '9',
        p_code: "27276-1HA0A",
        p_name: "ฝาปิดสำหรับ NISSAN MARCH แท้",
        imageUrl:'F-036.jpg',
    },
    {
        id: '10',
        p_code: "27276-3TU0A",
        p_name: "ฝาปิดสำหรับ NISSAN TEANA'14(L33) ของแท้",
        imageUrl:'F-036.jpg',
    },
    {
        id: '11',
        p_code: "27276-4JA0A",
        p_name: "COVER NISSAN NAVARA NP300 ของแท้",
        imageUrl:'F-036.jpg',
    },
    {
        id: '12',
        p_code: "27276-JNZ0A",
        p_name: "ฝาปิดสำหรับ NISSAN TEANA'09 แท้",
        imageUrl:'F-036.jpg',
    },
    {
        id: '13',
        p_code: "52091300",
        p_name: "ฝาปิดตู้แอร์ ISUZU DDI 1.9,CHEV COROLADO แท้",
        imageUrl:'F-036.jpg',
    },
    {
        id: '14',
        p_code: "7801A856",
        p_name: "ฝาปิดตู้แอร์ MITSU MITSU MIRAGE,ATTRAGE,X-PANDER แท้",
        imageUrl:'F-036.jpg',
    },
    {
        id: '15',
        p_code: "C-001",
        p_name: "COVER TOYOTA VIGO(KM)",
        imageUrl:'F-036.jpg',
    },
    {
        id: '16',
        p_code: "C-002",
        p_name: "COVER ISUZU D-MAX'03 แบบแบน",
        imageUrl:'F-036.jpg',
    },
    {
        id: '17',
        p_code: "C-003",
        p_name: "COVER ISUZU D-MAX'12 แบบฝาสีขาวคู่กับ F-015",
        imageUrl:'F-036.jpg',
    },
    {
        id: '18',
        p_code: "C-004",
        p_name: "COVER MITSU TRTION'04-'14",
        imageUrl:'F-036.jpg',
    },
    {
        id: '19',
        p_code: "C-005",
        p_name: "COVER BRIO AMAZE BR-V MIBOLIO",
        imageUrl:'F-036.jpg',
    },
    {
        id: '20',
        p_code: "C-006",
        p_name: "ถาดสำหรับ HONDA JAZZ,CITY'03 (ALGOTECH)",
        imageUrl:'F-036.jpg',
    },
]